### ISSUE TITLE
Referencing template from ig's

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ig-template#1]
The following referencing of the template from IGs results in the error shown below:

ig.ini
template = **ch.fhir.ig.template#0.4.0**

```
Parameters: -ig ig.json -auto-ig-build -target https://build.fhir.org/ig/hl7ch/ch-ems/ -out /scratch/ig-build-temp-OMRNZC/repo

dir = /scratch/ig-build-temp-OMRNZC/repo, path = /usr/local/rvm/bin:/usr/local/rvm/rubies/ruby-2.5.1/bin:/usr/java/openjdk-15/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Run time = Monday, August 17, 2020 at 9:39:05 AM Coordinated Universal Time (2020-08-17T09:39:05Z)
Package Cache: var/lib/.fhir/packages                                            (00:00.0018)
Load Template from ch.fhir.ig.template#0.4.0                                     (00:00.0664)
2020-08-17 09:39:06.320 [main] INFO  o.h.f.u.c.BasePackageCacheManager [BasePackageCacheManager.java:76] Failed to resolve package ch.fhir.ig.template#0.4.0 from server: http://packages.fhir.org
2020-08-17 09:39:06.464 [main] INFO  o.h.f.u.c.BasePackageCacheManager [BasePackageCacheManager.java:76] Failed to resolve package ch.fhir.ig.template#0.4.0 from server: http://packages2.fhir.org/packages
Installing ch.fhir.ig.template#0.4.0 to the package cache
  Fetching:
  Installing:  done.
 Load Template from fhir.base.template#0.1.0                                     (00:02.0618)
2020-08-17 09:39:08.172 [main] INFO  o.h.f.u.c.BasePackageCacheManager [BasePackageCacheManager.java:76] Failed to resolve package fhir.base.template#0.1.0 from server: http://packages.fhir.org
2020-08-17 09:39:08.304 [main] INFO  o.h.f.u.c.BasePackageCacheManager [BasePackageCacheManager.java:76] Failed to resolve package fhir.base.template#0.1.0 from server: http://packages2.fhir.org/packages
Installing fhir.base.template#0.1.0 to the package cache
  Fetching:.
  Installing: . done.
IG template 'ch.fhir.ig.template#0.4.0' is not trusted.  No scripts will be executed (00:03.0246)
Publishing Content Failed: Unable to execute 'onLoad' in script 'scripts/ant.xml' as the template 'ch.fhir.ig.template#0.4.0' is not trusted (reason: has file extensions: [.gitignore]) (00:03.0890)
                                                                                 (00:03.0890)
Use -? to get command line help                                                  (00:03.0890)
                                                                                 (00:03.0890)
Stack Dump (for debugging):                                                      (00:03.0890)
org.hl7.fhir.exceptions.FHIRException: Unable to execute 'onLoad' in script 'scripts/ant.xml' as the template 'ch.fhir.ig.template#0.4.0' is not trusted (reason: has file extensions: [.gitignore])
	at org.hl7.fhir.igtools.templates.Template.runScriptTarget(Template.java:167)
	at org.hl7.fhir.igtools.templates.Template.onLoadEvent(Template.java:327)
	at org.hl7.fhir.igtools.publisher.Publisher.initializeFromIg(Publisher.java:1598)
	at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:1418)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:709)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:7944)
```

**Comment by oliveregger** [comment]
you can add now the template with 

template = ch.fhir.ig.template#current
