### ISSUE TITLE
searchform is not allowed to have a script element

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ig-template#14]
FHIR IG Publisher Version 1.6.6 (Git# d1dac76a7c14). Built 2024-04-23T09:27:48.515Z returns an error for our search template:

output​/searchform​.html​#​/html​/body​/script at Line 130, column 2	error	The <script> tag containing the javascript 'const site = 'file:/'... is illegal and not allowed on the HL7 cibuild - put the script in a .js file in a trusted template

probably two problems
- script tag not in a js file
- template is not trusted

**Comment by oliveregger** [comment]
introducing js leads to:

org.hl7.fhir.exceptions.FHIRException: Unable to execute 'onLoad' in script 'scripts/ant.xml' as the template 'ch.fhir.ig.template#current' is not trusted (reason: Template has file extensions: [.js])
	at org.hl7.fhir.igtools.templates.Template.runScriptTarget(Template.java:193)
	at org.hl7.fhir.igtools.templates.Template.onLoadEvent(Template.java:375)
	at org.hl7.fhir.igtools.publisher.Publisher.initializeFromIg(Publisher.java:2650)
	at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:2491)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:988)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:12543)

**Comment by oliveregger** [comment]
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Trusted.20Template.20Process
